### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by haddigan** [haddigan/reactnd-readable#1]
## Default (Root)
- [x] should list all available categories, which should link to a category view for that category
- [x] should list all of the posts ordered by voteScore (highest score first)
- [x] should have a control for changing the sort method for the list, including at minimum, order by voteScore and order by timestamp
- [x] should have a control for adding a new post
## Category View
- [x] should list all available categories, which should link to a category view for that category
- [x] should list all of the posts ordered by voteScore (highest score first)
- [x] should have a control for changing the sort method for the list, including at minimum, order by voteScore and order by timestamp
- [x] should have a control for adding a new post
- [x] identical to the default view, but filtered to only include posts with the selected category
## Post Detail View
- [x] should show the details of a post, including: Title, Body, Author, timestamp (in user readable format), and vote score
- [x] should list all of the comments for that post, ordered by voteScore (highest first)
- [x] should have controls to edit or delete the post
- [x] should have a control to add a new comment.
- [x] implement comment form however you want (inline, modal, etc.)
- [x] comments should also have controls for editing or deleting
## Create/Edit View
- [x] should have a form to create new post or edit existing posts
- [x] when editing, existing data should be populated in the form
